### ISSUE TITLE
Tailwind precomplieエラーの件

### ISSUE THREAD

**Issue by lei900** [Kei5665/political_question_app#45]
Github actionsでテストを実行したとき、
AssetNotFoundエラーが出ている。

# ------------------

     ActionView::Template::Error:
       The asset "tailwind.css" is not present in the asset pipeline.

# ------------------
      # --- Caused by: ---
      # Sprockets::Rails::Helper::AssetNotFound:
      #   The asset "tailwind.css" is not present in the asset pipeline.

[Action記録](https://github.com/Kei5665/tokyo_senkyo_matching/runs/8175862852?check_suite_focus=true)

下記でPrecompile assetジョブを追加したら、新しいエラーがでた。。
```
      - name: Precompile assets
        run: bin/rails assets:precompile
```
エラー内容
```
SassC::SyntaxError: Error: Function rgb is missing argument $green.
        on line 1 of stdin
>> -white{--tw-bg-opacity:1;background-color:rgb(255 255 255/var(--tw-bg-opacit
```

調べたら、いくつかの推測があるようで、一旦明日で詳細確認する
>It looks like for some reason your Tailwind compiled CSS is being fed into Sass and Sass doesn’t understand modern CSS color syntax (commaless rgb).

↑Tailwindが最新のcss構文を使っているが、SASSが最新のCSS構文を理解できていないことが原因だそう
同じような推測
https://stackoverflow.com/questions/71805735/error-function-rgb-is-missing-argument-green-in-sass
https://stackoverflow.com/questions/70662382/couldnt-deploy-rails-tailwind-on-heroku

Tailwindcss-railsの公式説明によると、
TailwindがモダンなCSS構文を使っているけど、sassが最新のCSS構文をまだ理解できていないため、sassc-rails gemをアンインストールするのが必要だそうです。
>Tailwind uses modern CSS features that are not recognized by the sassc-rails extension that was included by default in the Gemfile for Rails 6. In order to avoid any errors like SassC::SyntaxError, you must remove that gem from your Gemfile.
https://github.com/rails/tailwindcss-rails#conflict-with-sassc-rails

ただアンインストールしたら、またrails-adminがsassが必要だそうで、cannot load such file -- sasscエラーが出てしまいます...
```
W, [2022-09-04T10:50:18.143681 #2006]  WARN -- : Removed sourceMappingURL comment for missing asset 'rails_admin/popper.js.map' from /home/runner/work/tokyo_senkyo_matching/tokyo_senkyo_matching/vendor/bundle/ruby/3.1.0/gems/rails_admin-3.0.0/vendor/assets/javascripts/rails_admin/popper.js
W, [2022-09-04T[10](https://github.com/Kei5665/tokyo_senkyo_matching/runs/8175980506?check_suite_focus=true#step:5:11):50:18.156370 #2006]  WARN -- : Removed sourceMappingURL comment for missing asset 'rails_admin/bootstrap.js.map' from /home/runner/work/tokyo_senkyo_matching/tokyo_senkyo_matching/vendor/bundle/ruby/3.1.0/gems/rails_admin-3.0.0/vendor/assets/javascripts/rails_admin/bootstrap.js
rake aborted!
LoadError: cannot load such file -- sassc

```

>If you have this issue while running tests in your continuous integration, you need to precompile assets with:
bundle exec rake assets:precompile

↑上のように修正したけど、同じエラー出ている

https://stackoverflow.com/questions/70401077/rails-7-asset-pipeline-sasscsyntaxerror-with-tailwind/70665740#70665740

https://github.com/ntkme/sassc-embedded-shim-ruby/issues/7

https://github.com/tailwindlabs/tailwindcss/discussions/6738
https://github.com/rails/tailwindcss-rails/issues/153

**Comment by Kei5665** [comment]
なるほどですね！
もし解決に時間がかかりそうならここら辺のファイルは自動テストから外しても良いかもです！
